### ISSUE TITLE
Burp Import Issues

### ISSUE THREAD

**Issue by 0x42424242** [ikkisoft/ParrotNG#1]
Hi, 

When trying and import the standalone JAR downloaded from https://github.com/ikkisoft/ParrotNG/releases I receive the following error message; 

```
java.lang.ClassNotFoundException: burp.BurpExtender
    at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:344)
    at burp.qub.a(Unknown Source)
    at burp.qub.<init>(Unknown Source)
    at burp.p8e.a(Unknown Source)
    at burp.syd.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)
```

In an attempt to rectify the issue I attempted to build it from the source. When trying to compile however I get the following error...

```
burp/BurpExtender.java:72: illegal start of type
                    List<IScanIssue> issues = new ArrayList<>(1);
                                                            ^
1 error
```

Any ideas? Help greatly appreciated.

**Comment by ikkisoft** [comment]
Which version of Java and Burp Pro? Also, which OS?

**Comment by 0x42424242** [comment]
Sorry for the lack of detail, I should have included that in the original post. 

Java Version: 1.8.0_31
Burp: Burpsuite Pro v1.6.12
OS: OSX 10.10

**Comment by ikkisoft** [comment]
Hi Peleus,

I tried the JAR on the exact same configuration and I was NOT able to reproduce this issue.
It looks like a problem with the classpath, but "burp.BurpExtender" is clearly in the jar and it's referenced in the MANIFEST.

Any additional information will be appreciated.

Thanks,
Luca

**Comment by stefanocoding** [comment]
Same problem here using Burp 1.6.20 on OS X.
However using BApp Store it was installed without any problem.

**Comment by ikkisoft** [comment]
Hi Stefano,
Which Java JRE? `java -version`

As a workaround, you could probably use `$ java -cp ./parrotng_v0.2.jar -jar burpsuite_pro_v1.6.20.jar`

**Comment by stefanocoding** [comment]
Hi Luca,
sorry for the delay.

```
$ java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
```

I haven't tried the workaround because it's working after I installed it via the BApp Store. Maybe there is something wrong with Burp. But it works, so not a problem.
